### ISSUE TITLE
Tried to donate but declined twice

### ISSUE THREAD

**Issue by tcsaddul** [jbaron/qx-typed#11]
I contacted my bank and it was not them who declined.
![Screenshot_20220112-150634_Chrome](https://user-images.githubusercontent.com/2255528/149089397-f4f76b5f-1654-41df-8d83-93f6bd02c5ed.jpg)

**Comment by jbaron** [comment]
Let me check it and come back to you.

**Comment by jbaron** [comment]
@tcsaddul First of all, thank you very much for your (attempted) donation, very generous and much appreciated!!! 

I opened a support ticket with PayPal to see if they can find something at their side, since in my account I don't see anything and with my own credit-card a donation just works fine. 

At the same time I'll try to see if there is another (more reliable) way for people to donate to the project. I'll keep you posted.

Kind regards,
Peter

**Comment by tcsaddul** [comment]
Ok sir. I will try again when I got good internet next wk. I donated 1k to the qooxdoo.org last december 2021 which succeeded but when I tried to donate the same for qxtyped, it failed so I tried again this January but failed 2nd time.

**Comment by jbaron** [comment]
@tcsaddul after further investigation, I made the following changes:

1. I added **Github Sponsorship**, hopefully this will work better. The link is also at the repo home page, but you can also use the following link directly: https://github.com/sponsors/jbaron?o=sd&sc=t 

   Hopefully this will solve the issue and prove to be more reliable than PayPal.

2. I regenerated the PayPal donation link. But since PayPal couldn't find anything wrong at their side, not sure if this wil actually solve the problem.
 

regards,
Peter

**Comment by tcsaddul** [comment]
I received confirmation from bank that it was successful thru sms. 

The payment was budgeted as a December bonus for 2021 just like we did the qooxdoo team last december.

Starting this year, I plan to donate on a yearly basis from now on. Do you prefer monthly?

Thank you for this amazing project.

**Comment by jbaron** [comment]
@tcsaddul   When I logged into my GitHub Sponsor page just now, I noticed a lot of confetti on my screen. Apparently they gamified that whenever there is a new donation you got to see confetti. So your donation has already been added to my GitHub  account :)

**Thanks you so very much for your generous donation!!!**

Regarding any future donations, I don't have a preference and yearly would be just fine (and of course only if you can really miss it).

Kind regards,
Peter

**Comment by tcsaddul** [comment]
Ok. For sure we will not miss it while using qx-typed. We plan to donate 2k usd per year from now on just like last year. The same amount for the qooxdoo team.
