### ISSUE TITLE
Upgrade qooxdoo version

### ISSUE THREAD

**Issue by yybalam** [jbaron/qx-typed#7]
Hello.

Is there some way for upgrade qooxdoo to a more resent version?

Thanks. :)

**Comment by tcsaddul** [comment]
Hello, 

The updated version is found in https://github.com/jbaron/cats
 

    On Thursday, July 7, 2016 5:05 AM, Yeye <notifications@github.com> wrote:
 

 Hello.Is there some way for upgrade qooxdoo to a more resent version?Thanks. :)—

**Comment by yybalam** [comment]
As I see on CATS, still in 4.1 version :sweat_smile: 

https://github.com/jbaron/cats/tree/master/resource

**Comment by jbaron** [comment]
Actually the declaration file in CATS is for 5.0 as far as I remember and should also work for 5.1. 

Perhaps indeed good to update this project also. Didn't do that at the time since when I created the declaration file it had some features that required the latest version of TypeScript. But now I suppose we can safely assume people are on 1.8 version of TypeScript.

**Comment by tcsaddul** [comment]
@Peter, thanks.  I confirm that it is indeed working on Typescript 1.8.x. Been using it since its release.
 

    On Saturday, July 9, 2016 6:08 PM, Peter <notifications@github.com> wrote:
 

 Actually the declaration file in CATS is for 5.0 as far as I remember and should also work for 5.1. Perhaps indeed good to update this project also. Didn't do that at the time since when I created the declaration file it had some features that required the latest version of TypeScript. But now I suppose we can safely assume people are on 1.8 version of TypeScript.—

**Comment by jbaron** [comment]
Updated both the declaration file and the qooxdoo.js file. Is now all based on the latest version of Qooxdoo  (5.0.1). Just let me know if there are any problems.

**Comment by tcsaddul** [comment]
Qooxdoo released version 5.0.2:  qooxdoo/qooxdoo

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
qooxdoo/qooxdoo
 qooxdoo - Universal JavaScript Framework  |   |

  |

  |

 
 

    On Monday, July 18, 2016 1:37 AM, Peter <notifications@github.com> wrote:
 

 Closed #7.—
